git before_commands:
  - "composer update --prefer-source"
tools:
  php_analyzer: 
    enabled: true
    filter: 
      paths: 
        - src/*
        - test/*
  php_code_coverage: 
    enabled: true
  php_code_sniffer: 
    enabled: true
  php_cpd: 
    enabled: true
    excluded_dirs: 
      - test
      - vendor
  php_cs_fixer: 
    config: 
      level: all
    enabled: true
    filter: 
      paths: 
        - src/*
        - test/*
  php_hhvm: 
    enabled: true
    filter: 
      paths:
        - src/*
        - test/*
  php_loc: 
    enabled: true
    excluded_dirs: 
      - test
      - vendor
  php_mess_detector: 
    enabled: true
    filter: 
      paths: 
        - src/*
  php_pdepend: 
    enabled: true
    excluded_dirs: 
      - test
      - vendor
  sensiolabs_security_checker: true